{% set name = "configmypy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/configmypy-{{ version }}.tar.gz
  sha256: a517921d18656844dae6831665cbf7718f153876b9cbc526f8bca6a6fb8cd28a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytest
    - pytest-mock
    - ruamel.yaml

test:
  imports:
    - configmypy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/JeanKossaifi/configmypy
  summary: Fast and easy configuration of Python projects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
